<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>EdenOnline_x64</AssemblyName>
    <Version>1.0.0</Version>


    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <PublishTrimmed>true</PublishTrimmed>
    <Configuration>Release</Configuration>
    <StripSymbols>true</StripSymbols>
    <Optimization>true</Optimization>
    <IsTrimmable>false</IsTrimmable>
    <NativeLib>Shared</NativeLib>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests/**</DefaultItemExcludes>

    <NoWarn>IL3002;IL2026;IL2065;IL3050;IL2069;IL3053;IDE0270;IDE0019;IL2062;IL3050;IL2026;IL2067;IL2070;IL2057;IL2075</NoWarn>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="linker.xml" />
    <ClCompile Include="exports.c" />
  </ItemGroup>

</Project>
